# Generated by Django 4.2 on 2026-06-18 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("image", "单张图片"),
                            ("batch", "批量图片"),
                            ("video", "视频"),
                            ("camera", "摄像头"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                        verbose_name="原始文件",
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="结果图片",
                    ),
                ),
                (
                    "result_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="结果视频",
                    ),
                ),
                (
                    "detection_time",
                    models.FloatField(blank=True, null=True, verbose_name="推理耗时(秒)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "total_objects",
                    models.IntegerField(default=0, verbose_name="检出目标总数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测记录",
                "verbose_name_plural": "检测记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField(verbose_name="类别ID")),
                ("class_name", models.CharField(max_length=50, verbose_name="类别名")),
                (
                    "class_name_cn",
                    models.CharField(default="", max_length=50, verbose_name="中文名"),
                ),
                ("confidence", models.FloatField(verbose_name="置信度")),
                ("xmin", models.IntegerField(verbose_name="X最小值")),
                ("ymin", models.IntegerField(verbose_name="Y最小值")),
                ("xmax", models.IntegerField(verbose_name="X最大值")),
                ("ymax", models.IntegerField(verbose_name="Y最大值")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="detection.detectionrecord",
                        verbose_name="所属记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测框",
                "verbose_name_plural": "检测框",
                "ordering": ["-confidence"],
            },
        ),
        migrations.AddIndex(
            model_name="detectionrecord",
            index=models.Index(
                fields=["user", "-created_at"], name="detection_d_user_id_ee16ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionrecord",
            index=models.Index(
                fields=["source_type"], name="detection_d_source__b552dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionrecord",
            index=models.Index(fields=["status"], name="detection_d_status_1e50ee_idx"),
        ),
    ]
